version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    restart: always
    networks:
      - music-social-network

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=app_password
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DB=app_db
    volumes:
      - ./backend:/app

volumes:
  mysql_data:

networks:
  music-social-network:
    driver: bridge 
